### ISSUE TITLE
App functions no longer work after uninstall and reinstall of app

### ISSUE THREAD

**Issue by benjwebster** [eclecticiq/intelligence-center-app-qradar#20] opened 2022-10-19 13:56 UTC
After uninstalling the application and reinstalling, the context menu functions no longer work as expected.

<img width="716" alt="image" src="https://user-images.githubusercontent.com/18141485/196710124-f5dd693a-f74f-422d-8bb1-259408126dfc.png">

<img width="483" alt="image" src="https://user-images.githubusercontent.com/18141485/196710186-1b530231-4643-4418-9872-cf8fc62c9964.png">

<img width="580" alt="image" src="https://user-images.githubusercontent.com/18141485/196710291-edacff26-3d88-4c63-a3e4-11053a29abf6.png">

<img width="474" alt="image" src="https://user-images.githubusercontent.com/18141485/196710362-a27403bc-cfba-4996-b5db-5e5e5b7840ee.png">

**Comment by puja-sacumen** [comment] 2022-11-02 10:29
Hi
I am unable to reproduce the above scenario.
I tried uninstalling and reinstalling the app , and after the set up is done. It is working fine.
Please let me know the exact steps to get the above scenario.

**Comment by benjwebster** [comment] 2022-11-07 13:48
1. Installed QRadar following guide [here](https://www.ibm.com/docs/en/qsip/7.4?topic=qcmi-configuring-qradar-743-virtual-appliance-amazon-web-services) for AWS instance deployment

_No additional changes made once installed_

2. Installed QRadar EclecticIQ application
3. Configured connection to EclecticIQ instance
4. Tested that lookup functionality and sighting creation work as expected
5. Uninstalled EclecticIQ app
6. Reinstalled EclecticIQ app
7. Configured connection to EclecticIQ instance again
8. Error encountered attempting to use lookup function

<img width="435" alt="image" src="https://user-images.githubusercontent.com/18141485/200326170-7c0e0745-b5ef-4873-989e-237e085a1dd6.png">

**Comment by puja-sacumen** [comment] 2022-11-16 09:13
We are unable to replicate the same scenario. This can probably be the browser cache issue. So you can try to clear cache and execute it once.
Also I am sharing the video link, where we have executed the above steps and the app is working fine.
https://drive.google.com/file/d/1KIGZLSxRT_SCoszNV_QsQA5Q0ZuI5NCg/view?usp=sharing

**Comment by benjwebster** [comment] 2022-11-16 09:32
Thanks for sharing the video to help confirm the steps taken.

I have not been able to resolve the issue with clearing the cache at any point of the process.

Can you confirm the version of QRadar you are using for testing? Your video does not show some of the same menu information, prompts and popups that I receive when working with the AWS marketplace image I linked to, which suggests the versions are different.

I am using version 7.4.3

<img width="770" alt="image" src="https://user-images.githubusercontent.com/18141485/202143224-dc7763d4-84b6-4093-a7c6-99ef247ed0ef.png">

**Comment by puja-sacumen** [comment] 2022-11-16 14:31
yes the previous one was for version 7.3 
We have tested the same for version 7.4 
Here is the video for your reference.
https://drive.google.com/file/d/1cIBtJfL7yqngo79htQMSJg6TfDFYITbn/view?usp=sharing

**Comment by himynamesdave** [comment] 2023-02-07 11:05
Marking as won't do as unable to recreate.

If you are able to offer more details on how to recreate, we can reopen this ticket.

**Closed as completed by himynamesdave** 2023-02-07 11:05 UTC
Labels: bug, question
